default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['APP_DB_HOST'] || 'localhost' %>
  database: <%= ENV['APP_DB_NAME'] %>
  username: <%= ENV['APP_DB_USERNAME'] || 'root' %>
  password: <%= ENV['APP_DB_PASSWORD'] || '' %>
  port: 5432

development:
  <<: *default
  database: hyper_kitten_meow_development
test:
  <<: *default
  database: hyper_kitten_meow_test

